name: Initialize Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REPO_NAME: ${{ github.event.repository.name }}

permissions:
  contents: write

jobs:
  setup-pages:
    runs-on: ubuntu-latest
    if: ${{ vars.INITED != 'true' }}
    steps:
      - name: Configure GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.ADMIN_PAT }}
          REPO: ${{ github.repository }}
        run: |
          echo "Creating Pages ..."
          gh api -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/$REPO/pages \
            -f 'source[branch]=main' -f 'source[path]=/' -f 'build_type=workflow'
  
  set-repo-var:
    runs-on: ubuntu-latest
    if: ${{ vars.INITED != 'true' }}
    steps:
      - name: Set up variables
        env:
          GH_TOKEN: ${{ secrets.ADMIN_PAT }}
          REPO: ${{ github.repository }}
        run: |
          # Define variable name and value
          VAR_NAME="INITED"
          VAR_VALUE="true"

          echo "Creating variable $VAR_NAME..."
          gh api \
            -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            /repos/$REPO/actions/variables \
            -f name="$VAR_NAME" \
            -f value="$VAR_VALUE"
  
  rename-and-push:
    runs-on: ubuntu-latest
    needs: [setup-pages, set-repo-var]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Rename files
        run: |
          echo "Renaming files to use repository name ..."
          find . -type f -print0 | xargs -0 -I {} sed -i "s/quickstart/$REPO_NAME/g" {}
          mv src/quickstart src/$REPO_NAME

      - name: Delete init workflow file
        run: |
          rm -f .github/workflows/init.yml
      
      - name: Fix possible index corruption
        run: |
          rm -f .git/index
          git reset

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Checking for changes to commit ..."
          git status

          if ! git diff-index --quiet HEAD --; then
            echo "Pushing changes to remote repository ..."
            git add .
            git commit --amend --no-edit
            git push --force
          else
            echo "No changes to commit."
          fi
      
      - name: Setup develop branch
        run: |
          git checkout -b develop
          git push -u origin develop
      
      - name: Rerun other workflows
        env:
          GH_TOKEN: ${{ secrets.ADMIN_PAT }}
          WORKFLOWS: "deploy-pages.yml pytest.yml"
        run: |
          echo "Rerunning workflows ..."
          for WORKFLOW in $WORKFLOWS; do
            echo "Triggering workflow: $WORKFLOW"
            gh workflow run "$WORKFLOW" --ref main
          done