name: Renamer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  setup-pages:
    runs-on: ubuntu-latest
    if: ${{ vars.INITED }} != 'true'
    steps:
      - name: Configure GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "Setting Pages source to GitHub Actions..."
          gh api -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/$REPO/pages \
            -f source=workflow
  
  set-repo-var:
    runs-on: ubuntu-latest
    if: ${{ vars.INITED }} != 'true'
    steps:
      - name: Set up variables
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          # Define variable name and value
          VAR_NAME="INITED"
          VAR_VALUE="true"

          # Check if variable exists
          EXIST=$(gh api repos/$REPO/actions/variables/$VAR_NAME -H "Authorization: token $GH_TOKEN" || echo "notfound")

          if [[ "$EXIST" == "notfound" ]]; then
            echo "Creating variable $VAR_NAME..."
            gh api \
              -X POST \
              -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              /repos/$REPO/actions/variables \
              -f name="$VAR_NAME" \
              -f value="$VAR_VALUE"
          else
            echo "Updating variable $VAR_NAME..."
            gh api \
              -X PATCH \
              -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              /repos/$REPO/actions/variables/$VAR_NAME \
              -f value="$VAR_VALUE"
          fi
  
  rename-and-push:
    runs-on: ubuntu-latest
    needs: [setup-pages, set-repo-var]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Rename files
        run: |
          find . -type f -print0 | xargs -0 -I {} sed -i "s/quickstart/$REPO_NAME/g" {}
          mv src/quickstart src/$REPO_NAME
      - name: Delete this file
        run: |
          rm -f .github/workflows/init.yml
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Renamed files via GitHub Actions" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}