name: Initialize Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REPO_NAME: ${{ github.event.repository.name }}

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-pages:
    runs-on: ubuntu-latest
    if: ${{ vars.INITED != 'true' }}
    steps:
      - name: Configure GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.ADMIN_PAT }}
          REPO: ${{ github.repository }}
        run: |
          echo "Creating Pages ..."
          gh api -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/$REPO/pages \
            -f 'source[branch]=main' -f 'source[path]=/' -f 'build_type=workflow'
  
  set-repo-var:
    runs-on: ubuntu-latest
    if: ${{ vars.INITED != 'true' }}
    steps:
      - name: Set up variables
        env:
          GH_TOKEN: ${{ secrets.ADMIN_PAT }}
          REPO: ${{ github.repository }}
        run: |
          # Define variable name and value
          VAR_NAME="INITED"
          VAR_VALUE="true"

          echo "Creating variable $VAR_NAME..."
          gh api \
            -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            /repos/$REPO/actions/variables \
            -f name="$VAR_NAME" \
            -f value="$VAR_VALUE"
  
  rename-and-push:
    runs-on: ubuntu-latest
    needs: [setup-pages, set-repo-var]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          clean: true

      - name : Create a new branch
        run: |
          git checkout -b init-temp

      - name: Rename files
        run: |
          echo "Renaming files to use repository name ..."
          find . -type f -print0 | xargs -0 -I {} sed -i "s/quickstart/$REPO_NAME/g" {}
          mv src/quickstart src/$REPO_NAME

      - name: Delete init workflow file
        run: |
          rm -f .github/workflows/init.yml

      - name: Rebuild git index safely
        run: |
          rm -rf .git/index
          git add .

      - name: Commit on a new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Checking for changes to commit ..."
          git status

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Pushing changes to remote repository ..."
            git commit -m "Initialize repository"
          fi
          git push origin init-temp --force

      - name: Create PR and squash merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh pr create \
            --repo $GITHUB_REPOSITORY \
            --title "Initialize Repository" \
            --body "This PR initializes the repository automatically" \
            --head init-temp \
            --base main \
            --fill
          gh pr merge 1 \
            --repo $GITHUB_REPOSITORY \
            --squash \
            --delete-branch
